pipeline:
  build:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: edsonhaibu
    password: haibu2017. 
    email: edson.perez@haibu.cl
    repo: edsonhaibu/haibu-smart-arauco
    dockerfile: Dockerfile
    tag: 
      - latest
    insecure: false
    when:
      branch: master
