pipeline:
  pre-build:
    image: node:latest
    commands:
      - npm install
      - npm install gulp -g
      - npm install bower -g
      - bower install --allow-root
      - gulp clean
      - gulp build
  build:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: edsonhaibu
    password: haibu2017. 
    email: edson.perez@haibu.cl
    repo: edsonhaibu/haibu-smart-arauco
    dockerfile: Dockerfile
    tag: 
      - latest
    insecure: false
    when:
      branch: master
