pipeline:
#  pre-build:
#    image: node:latest
#    commands:
#      - npm install
#      - npm install gulp -g
#      - npm install bower -g
#      - bower install --allow-root
#      - gulp clean
#      - gulp build
  build:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: edsonhaibu
    password: haibu2017. 
    repo: edsonhaibu/haibu-smart-arauco
    dockerfile: Dockerfile
    tag: 
      - latest
    insecure: false
    when:
      branch: master
  deploy:
    image: appleboy/drone-ssh	
    hots: 67.205.144.184
    username: root
    password: haibu2017.
    port: 22
    pull: true
    script:
      - echo hello
      - echo world
      - docker pull edsonhaibu/haibu-smart-arauco
      - docker stop arauco
      - docker rm arauco
      - docker run -p 84:80 --name arauco edsonhaibu/haibu-smart-arauco
  notify:
    image: drillster/drone-email
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    host: smtp.gmail.com
    port: 465
    from: no-reply@haibu.cl
    username: no-reply@haibu.cl
    password: haibu2017.
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
    template: >
      https://git.io/vgvPz
    when:
      status: [ success, failure ]
