pipeline:
 build:
   image: node:latest
   mem_limit: 1000000000
   commands:
     - npm install
     - npm install gulp -g
     - npm install bower -g
     - bower install --allow-root
     - gulp clean
     - gulp build
 publish:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [ docker_username, docker_password ]
    repo: edsonhaibu/haibu-smart-arauco
    dockerfile: Dockerfile
    tag: 
      - latest
    insecure: false
    when:
      branch: master
 deploy:
    image: appleboy/drone-ssh
    host: iot.haibusmart.com
    username: root
    secrets: [ ssh_password ]
    command_timeout: 300
    port: 22
    script:
      - docker stop arauco
      - docker rm arauco
      - docker pull edsonhaibu/haibu-smart-arauco
      - docker run -d -p 84:80 --name arauco edsonhaibu/haibu-smart-arauco
    when:
      status: [ success ]
      branch: master
 notify:
    image: drillster/drone-email
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    host: smtp.gmail.com
    port: 465
    from: no-reply@haibu.cl
    secrets: [ email_password , email_username, email_recipients ]
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
    template: >
      https://git.io/vgvPz
    when:
      status: [ success, failure ]
      branch: master